import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { PsuPowerRequirementUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Calculateur de puissance du bloc PSU';
const description = 'Estimez la puissance du bloc d alimentation nécessaire pour votre PC selon la consommation des composants, la marge de transitoire, la réserve d évolution et le bloc installé.';
const faq = [
  { question: 'Comment calculer la puissance PSU nécessaire pour un PC ?', answer: 'Additionnez la puissance prévue du processeur, de la carte graphique, de la carte mère, du stockage, des ventilateurs et des périphériques. Ajoutez ensuite une marge de transitoire et une réserve d évolution, puis arrondissez vers une puissance pratique.' },
  { question: 'Faut-il utiliser le TDP ou une mesure de consommation ?', answer: 'Utilisez une mesure ou la puissance de carte indiquée par le fabricant lorsqu elle existe. Le TDP sert à planifier, mais ne garantit pas le maximum consommé par chaque charge. Gardez une marge et vérifiez les spécifications des composants.' },
  { question: 'Que représente la marge de transitoire ?', answer: 'Elle couvre les pointes brèves et l incertitude des estimations de charge soutenue. Elle évite de dimensionner le bloc exactement au niveau de la charge normale.' },
  { question: 'Pourquoi un bloc très puissant peut-il être un mauvais choix ?', answer: 'Un bloc très surdimensionné peut coûter davantage et fonctionner loin de sa meilleure plage de rendement. Vérifiez aussi les connecteurs, le format, les rails et la compatibilité de la plateforme.' },
  { question: 'Quelle différence entre PSU minimale et PSU recommandée ?', answer: 'La PSU minimale couvre la charge calculée et la marge de transitoire. La PSU recommandée ajoute une réserve d évolution pour les mises à niveau et les incertitudes.' },
  { question: 'Comment les pics de la carte graphique influencent-ils le choix ?', answer: 'Une carte graphique peut dépasser brièvement sa puissance soutenue. Gardez une marge, consultez les indications du fabricant et vérifiez les connecteurs ainsi que la réponse aux transitoires du bloc.' },
  { question: 'Un calculateur de watts suffit-il pour choisir un bloc ?', answer: 'Non. Vérifiez aussi le format, les connecteurs, la compatibilité, les protections, la certification de rendement, la garantie et les tests indépendants.' },
];
const howTo = [
  { name: 'Saisir la puissance des composants', text: 'Ajoutez des valeurs réalistes pour le processeur, la carte graphique, la carte mère, le stockage, les ventilateurs et les périphériques.' },
  { name: 'Indiquer le bloc installé', text: 'Saisissez la puissance inscrite sur votre bloc actuel ou zéro pour préparer une nouvelle configuration.' },
  { name: 'Régler les marges de planification', text: 'Utilisez la marge de transitoire pour les pointes et la marge d évolution pour les extensions futures.' },
  { name: 'Lire la recommandation', text: 'Comparez les valeurs minimale et recommandée à votre bloc actuel et utilisez le statut comme signal de planification.' },
  { name: 'Vérifier la compatibilité', text: 'Confirmez le format, les connecteurs, les exigences de la carte graphique et les recommandations du fabricant.' },
];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'fr' };

export const content: ToolLocaleContent<PsuPowerRequirementUI> = {
  slug: 'calculateur-puissance-alimentation-ordinateur', title, description, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Calculateur de puissance PSU pour PC', level: 2 }, { type: 'paragraph', html: 'Estimez la puissance du bloc nécessaire à partir de la charge prévue de chaque composant. Le calcul sépare charge de base, transitoires, réserve d évolution, minimum et recommandation pour comparer votre bloc aux besoins de la configuration.' },
    { type: 'title', text: 'Fonctionnement de l estimation', level: 3 }, { type: 'paragraph', html: 'La charge de base additionne processeur, carte graphique, carte mère, stockage, ventilateurs et périphériques. Le calcul ajoute une marge pour les pointes et une marge pour les changements futurs, puis arrondit au palier pratique de 50 watts.' },
    { type: 'table', headers: ['Entrée', 'Rôle', 'Conseil'], rows: [['Processeur', 'Détermine une grande partie de la charge soutenue', 'Utilisez une puissance mesurée ou celle prévue pour la charge.'], ['Carte graphique', 'Souvent la charge principale en jeu', 'Utilisez la puissance de carte et prévoyez les pointes.'], ['Carte mère et mémoire', 'Couvre la consommation de la plateforme', 'Incluez chipset, mémoire, régulation et appareils intégrés.'], ['Stockage et ventilation', 'Ajoute consommation continue et démarrage', 'Comptez chaque disque, pompe et ventilateur.'], ['Marges', 'Protègent contre incertitudes et évolutions', 'Augmentez-les si les données sont incertaines.']] },
    { type: 'title', text: 'Choisir une puissance sûre', level: 3 }, { type: 'list', items: ['Comparez les valeurs minimale et recommandée.', 'Vérifiez les connecteurs et le format du bloc.', 'Confirmez la compatibilité avec les transitoires de la carte graphique.', 'Traitez le résultat comme une estimation et vérifiez les caractéristiques finales.'] },
    { type: 'title', text: 'Comprendre le statut du bloc actuel', level: 3 }, { type: 'paragraph', html: 'Un bloc sous le minimum est insuffisant. Entre minimum et recommandation, la marge est limitée. Un bloc au niveau recommandé offre une réserve pratique, tandis qu un modèle très puissant peut dépasser les besoins de la configuration.' },
    { type: 'title', text: 'Puissance minimale et puissance recommandée', level: 3 }, { type: 'paragraph', html: 'Le minimum est un seuil calculé, pas toujours une cible d achat lorsque les données sont incertaines. La recommandation ajoute de la place pour les pointes et les évolutions. Le format du boîtier et les connecteurs de la carte graphique restent à vérifier.' },
    { type: 'title', text: 'Transitoires GPU et contrôle de la plateforme', level: 3 }, { type: 'paragraph', html: 'Les cartes graphiques peuvent produire des pointes absentes d une simple valeur soutenue. La marge de transitoire aide à planifier, mais ne remplace pas les indications des fabricants. Vérifiez câbles PCIe, exigences ATX, protections et essais indépendants.' },
    { type: 'table', headers: ['Situation', 'Approche', 'Vérifications'], rows: [['Mesures connues', 'Mesure avec marge modérée', 'Charge, pointes et connecteurs'], ['Nouvelle configuration gaming', 'Puissance de carte avec réserve', 'Transitoires GPU, câbles et format'], ['Évolutions prévues', 'Réserve de croissance supérieure', 'Disques, cartes, refroidissement et boîtier'], ['Matériel incertain', 'Valeurs prudentes sans viser le minimum', 'Données fabricant et tests indépendants']] },
    { type: 'title', text: 'Ce que le calculateur ne peut pas confirmer', level: 3 }, { type: 'paragraph', html: 'L outil estime une capacité à partir de vos entrées. Il ne peut pas confirmer qu un modèle précis est authentique, silencieux, bien protégé ou adapté à tous les transitoires. Validez la pièce finale avec les données officielles et des tests sérieux.' },
  ],
  ui: { sceneKicker: 'Constellation énergétique', deckTitle: 'Réglez les canaux', deckHint: 'Faites glisser un canal pour voir la sculpture réagir', presetsHeader: 'Profils de configuration', officePreset: 'Bureautique', gamingPreset: 'Gaming', highEndPreset: 'Haut de gamme', workstationPreset: 'Station de travail', miniPcPreset: 'Mini PC', componentsHeader: 'Charge des composants', cpuWatts: 'Processeur', gpuWatts: 'Carte graphique', motherboardWatts: 'Carte mère et mémoire', storageWatts: 'Stockage', fansWatts: 'Ventilateurs et refroidissement', peripheralsWatts: 'Périphériques', currentPsuWatts: 'Puissance du bloc actuel', showAdvanced: 'Régler les charges détaillées', hideAdvanced: 'Masquer les charges détaillées', marginsHeader: 'Marges de planification', transientMargin: 'Marge de transitoire', growthMargin: 'Marge d évolution', wattsUnit: 'W', baseLoad: 'Charge de base', minimumPsu: 'PSU minimale', recommendedPsu: 'PSU recommandée', currentPsu: 'PSU actuelle', headroom: 'Réserve', statusLabel: 'État de la configuration', statusInsufficient: 'Insuffisante', statusTight: 'Limitée', statusRecommended: 'Recommandée', statusOversized: 'Surdimensionnée', summaryPrefix: 'Prochaine étape:', diagramTitle: 'Observatoire de puissance', currentMarker: 'PSU actuelle', minimumMarker: 'Minimum', recommendedMarker: 'Recommandée', adviceInsufficient: 'Choisissez une PSU au niveau recommandé et vérifiez les connecteurs de la carte graphique.', adviceTight: 'La configuration est proche de la limite. Choisissez la recommandation pour garder de la marge.', adviceRecommended: 'Votre PSU actuelle atteint la cible. Vérifiez connecteurs, format et plateforme.', adviceOversized: 'La capacité est large. Contrôlez rendement, espace et connecteurs avant l achat.', inputHint: 'Utilisez des valeurs mesurées lorsque possible. Le résultat est une estimation et ne remplace pas la vérification des spécifications finales.' },
};
