import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { PsuPowerRequirementUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'Calcolatore del fabbisogno PSU';
const description = 'Stima la potenza dell alimentatore necessaria per il PC in base ai consumi dei componenti, al margine dei transitori, alla riserva per gli aggiornamenti e alla PSU installata.';
const faq = [
  { question: 'Come calcolo la potenza PSU necessaria per un PC?', answer: 'Somma la potenza prevista di processore, scheda grafica, scheda madre, archiviazione, ventole e periferiche. Aggiungi poi un margine per i transitori e una riserva di crescita prima di arrotondare a una potenza pratica.' },
  { question: 'Devo usare il TDP o un valore misurato?', answer: 'Usa un valore misurato o la board power indicata dal produttore quando disponibile. Il TDP aiuta a pianificare ma non garantisce il massimo consumo di ogni carico. Mantieni margine e controlla le specifiche.' },
  { question: 'Che cosa indica il margine dei transitori?', answer: 'Tiene conto dei picchi brevi e dell incertezza nelle stime del consumo sostenuto. Evita di dimensionare l alimentatore esattamente sulla normale richiesta del sistema.' },
  { question: 'Perché un alimentatore molto grande può essere una scelta sbagliata?', answer: 'Un modello sovradimensionato può costare di più e lavorare lontano dalla sua zona di rendimento migliore. Controlla anche formato, connettori, rail e compatibilità della piattaforma.' },
  { question: 'Qual è la differenza tra PSU minima e consigliata?', answer: 'La PSU minima copre il carico calcolato più il margine dei transitori. La PSU consigliata aggiunge una riserva per gli aggiornamenti e le incertezze future.' },
  { question: 'Come incidono i picchi della GPU sulla scelta?', answer: 'Una scheda grafica può superare per brevi istanti la propria potenza sostenuta. Usa una riserva, segui le indicazioni del produttore e verifica connettori e risposta ai transitori.' },
  { question: 'Basta un calcolatore di watt per scegliere un alimentatore?', answer: 'No. Verifica anche formato, connettori, compatibilità, protezioni, certificazione di efficienza, garanzia e test indipendenti.' },
];
const howTo = [{ name: 'Inserisci la potenza dei componenti', text: 'Aggiungi valori realistici per processore, scheda grafica, scheda madre, archiviazione, ventole e periferiche.' }, { name: 'Indica la PSU installata', text: 'Inserisci la potenza dell alimentatore che possiedi oppure zero per un nuovo PC.' }, { name: 'Regola i margini di progetto', text: 'Usa il margine dei transitori per i picchi e quello di crescita per dischi, schede e aggiornamenti futuri.' }, { name: 'Leggi la raccomandazione', text: 'Confronta i valori minimo e consigliato con la PSU attuale e usa lo stato come guida.' }, { name: 'Controlla la compatibilità', text: 'Verifica formato, connettori, requisiti della GPU e indicazioni del produttore prima dell acquisto.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'EUR' }, inLanguage: 'it' };

export const content: ToolLocaleContent<PsuPowerRequirementUI> = {
  slug: 'calcolatore-potenza-alimentatore-computer', title, description, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [
    { type: 'title', text: 'Calcolatore della potenza PSU per PC', level: 2 }, { type: 'paragraph', html: 'Stima la potenza dell alimentatore partendo dal carico previsto di ogni componente. Il calcolo separa carico base, transitori, riserva per gli aggiornamenti, PSU minima e PSU consigliata per confrontare il tuo alimentatore con le esigenze del sistema.' },
    { type: 'title', text: 'Come funziona la stima', level: 3 }, { type: 'paragraph', html: 'Il carico base è la somma di processore, scheda grafica, scheda madre, archiviazione, ventole e periferiche. Il calcolo aggiunge margine per i picchi e per le modifiche future, poi arrotonda al successivo intervallo pratico di 50 watt.' },
    { type: 'table', headers: ['Ingresso', 'Perché conta', 'Indicazione'], rows: [['Processore', 'Definisce una parte importante del carico continuo', 'Usa la potenza del package o un valore misurato.'], ['Scheda grafica', 'Spesso è il carico principale nei giochi', 'Usa la board power e considera i picchi.'], ['Scheda madre e memoria', 'Copre il consumo della piattaforma', 'Includi chipset, memoria, regolazione e dispositivi integrati.'], ['Archiviazione e ventole', 'Aggiungono consumo continuo e di avvio', 'Conta ogni unità, pompa e ventola.'], ['Margini', 'Proteggono da incertezza e aggiornamenti', 'Aumentali quando i dati non sono sicuri.']] },
    { type: 'title', text: 'Scegliere una potenza sicura', level: 3 }, { type: 'list', items: ['Confronta i valori minimo e consigliato.', 'Controlla formato e connettori della PSU.', 'Verifica il comportamento della scheda grafica.', 'Considera il risultato una stima e controlla le specifiche finali.'] },
    { type: 'title', text: 'Leggere lo stato della PSU attuale', level: 3 }, { type: 'paragraph', html: 'Una PSU sotto il minimo non basta per i valori inseriti. Tra minimo e consiglio la riserva è ridotta. Una PSU consigliata offre spazio pratico, mentre un modello enorme può fornire più capacità del necessario.' },
    { type: 'title', text: 'Potenza minima e potenza consigliata', level: 3 }, { type: 'paragraph', html: 'Il minimo è una soglia calcolata e non sempre un obiettivo di acquisto quando i dati sono incerti. Il valore consigliato aggiunge spazio per picchi e modifiche future. Formato del case e connettori della GPU devono comunque essere compatibili.' },
    { type: 'title', text: 'Transitori della GPU e controllo della piattaforma', level: 3 }, { type: 'paragraph', html: 'Le schede grafiche possono generare picchi brevi che non compaiono nella potenza sostenuta. Il margine aiuta a pianificare ma non sostituisce le indicazioni dei produttori. Controlla cavi PCIe, requisiti ATX, protezioni e test indipendenti.' },
    { type: 'table', headers: ['Situazione', 'Approccio', 'Controlli'], rows: [['Valori misurati', 'Usa la misura con margine moderato', 'Carico, picchi e connettori'], ['Nuovo PC gaming', 'Usa board power e riserva di crescita', 'Transitori GPU, cavi e formato'], ['Aggiornamenti previsti', 'Aumenta la riserva prima di arrotondare', 'Dischi, schede, raffreddamento e case'], ['Hardware incerto', 'Usa valori prudenti senza comprare al minimo', 'Dati del produttore e test indipendenti']] },
    { type: 'title', text: 'Che cosa non può confermare il calcolatore', level: 3 }, { type: 'paragraph', html: 'Lo strumento stima la capacità dai valori inseriti. Non può confermare che un modello sia autentico, silenzioso, ben protetto o adatto a ogni transitorio. Valida il modello finale con dati ufficiali e test hardware affidabili.' },
  ],
  ui: { sceneKicker: 'Costellazione energetica', deckTitle: 'Regola i canali', deckHint: 'Trascina un canale per far reagire la scultura', presetsHeader: 'Preset della build', officePreset: 'Ufficio', gamingPreset: 'Gaming', highEndPreset: 'Fascia alta', workstationPreset: 'Workstation', miniPcPreset: 'Mini PC', componentsHeader: 'Carico dei componenti', cpuWatts: 'Processore', gpuWatts: 'Scheda grafica', motherboardWatts: 'Scheda madre e memoria', storageWatts: 'Archiviazione', fansWatts: 'Ventole e raffreddamento', peripheralsWatts: 'Periferiche', currentPsuWatts: 'Potenza PSU attuale', showAdvanced: 'Regola i carichi dettagliati', hideAdvanced: 'Nascondi i carichi dettagliati', marginsHeader: 'Margini di pianificazione', transientMargin: 'Margine dei transitori', growthMargin: 'Margine di crescita', wattsUnit: 'W', baseLoad: 'Carico base', minimumPsu: 'PSU minima', recommendedPsu: 'PSU consigliata', currentPsu: 'PSU attuale', headroom: 'Riserva', statusLabel: 'Stato della build', statusInsufficient: 'Insufficiente', statusTight: 'Al limite', statusRecommended: 'Consigliata', statusOversized: 'Sovradimensionata', summaryPrefix: 'Prossimo passo:', diagramTitle: 'Osservatorio della potenza', currentMarker: 'PSU attuale', minimumMarker: 'Minima', recommendedMarker: 'Consigliata', adviceInsufficient: 'Scegli una PSU almeno pari al valore consigliato e verifica i connettori della scheda grafica.', adviceTight: 'La build è vicina al limite. Scegli il valore consigliato per avere spazio agli aggiornamenti.', adviceRecommended: 'La PSU attuale supera l obiettivo. Verifica connettori, formato e piattaforma.', adviceOversized: 'La capacità è ampia. Controlla rendimento, spazio e connettori prima dell acquisto.', inputHint: 'Usa valori misurati quando possibile. Il risultato è una stima di pianificazione e non sostituisce il controllo delle specifiche finali.' },
};
