import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { PsuPowerRequirementUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'PSU電源容量計算ツール';
const description = '各コンポーネントの消費電力、瞬間的な負荷の余裕、将来の増設分、現在のPSU容量からPCに必要な電源容量を見積もります。';
const faq = [{ question: 'PCに必要なPSU容量はどう計算しますか？', answer: 'プロセッサー、グラフィックスカード、マザーボード、ストレージ、ファン、周辺機器の消費電力を合計します。次に瞬間的な負荷の余裕と将来の増設分を加え、実用的な電源容量に切り上げます。' }, { question: 'TDPと実測消費電力のどちらを使うべきですか？', answer: '可能なら実測値またはメーカーが示すボード電力を使います。TDPは計画用の値であり、すべての負荷における最大消費電力を保証しません。余裕を残して仕様も確認してください。' }, { question: '瞬間負荷マージンとは何ですか？', answer: '短時間の電力ピークと持続負荷の推定誤差を考慮する余裕です。通常の消費電力ぎりぎりで電源を選ぶことを防ぎます。' }, { question: '大容量すぎるPSUがよくない場合はありますか？', answer: '過剰な容量の電源は高価になり、効率のよい動作範囲から外れることがあります。サイズ、コネクター、系統、プラットフォームの互換性も確認してください。' }, { question: '最小PSUと推奨PSUの違いは何ですか？', answer: '最小PSUは計算したコンポーネント負荷と瞬間負荷マージンを満たす値です。推奨PSUはさらに増設の余裕を加え、将来の変更や不確実性に対応します。' }, { question: 'GPUの電力スパイクはPSU選びにどう影響しますか？', answer: 'グラフィックスカードは持続電力を短時間超えることがあります。マージンを確保し、メーカーの指示と必要なコネクター、電源の過渡応答を確認してください。' }, { question: 'ワット数計算だけでPSUを選べますか？', answer: 'いいえ。サイズ、コネクター、互換性、保護機能、効率認証、保証、独立した品質テストも確認が必要です。' }];
const howTo = [{ name: 'コンポーネントの電力を入力する', text: 'プロセッサー、グラフィックスカード、マザーボード、ストレージ、ファン、周辺機器の現実的な値を入力します。' }, { name: '現在のPSUを設定する', text: '使用中の電源に表示された容量を入力します。新しいPCを計画する場合はゼロを入力します。' }, { name: '計画マージンを調整する', text: '短いピークには瞬間負荷マージンを、増設には成長マージンを使います。' }, { name: '推奨値を読む', text: '最小値と推奨値を現在のPSUと比較し、状態表示を計画の目安にします。' }, { name: 'ハードウェアの適合を確認する', text: '購入前にサイズ、コネクター、GPU要件、メーカーの指示を確認します。' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'JPY' }, inLanguage: 'ja' };

export const content: ToolLocaleContent<PsuPowerRequirementUI> = {
  slug: 'psu-power-requirement-calculator', title, description, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [{ type: 'title', text: 'PC向けPSU電源容量計算ツール', level: 2 }, { type: 'paragraph', html: '各コンポーネントの予想負荷から、PCに必要な電源容量を見積もります。基本負荷、瞬間負荷、増設用の余裕、最小容量、推奨容量を分けて表示するため、現在の電源とシステムの必要量を比較できます。' }, { type: 'title', text: '電源容量の計算方法', level: 3 }, { type: 'paragraph', html: '基本負荷はプロセッサー、グラフィックスカード、マザーボード、ストレージ、ファン、周辺機器の合計です。短いピークと将来の変更に備える余裕を加え、実用的な50ワット単位に切り上げます。' }, { type: 'table', headers: ['入力', '重要な理由', '計画の目安'], rows: [['プロセッサー電力', '持続負荷の大部分を決める', 'パッケージ電力または実測値を使う。'], ['グラフィックスカード電力', 'ゲームでは大きな負荷になりやすい', 'ボード電力と短いピークを考慮する。'], ['マザーボードとメモリ', 'プラットフォームの消費を含む', 'チップセット、メモリ、電源回路、内蔵機器を含める。'], ['ストレージとファン', '連続負荷と起動時負荷を加える', '各ドライブ、ポンプ、ファンを含める。'], ['マージン', '不確実性と増設に備える', 'データが不確かな場合は増やす。']] }, { type: 'title', text: '安全なPSU容量を選ぶ', level: 3 }, { type: 'list', items: ['最小値と推奨値を比較する。', '電源のサイズとコネクターを確認する。', 'GPUの電力特性に対応できるか確認する。', '結果は推定値として扱い、最終仕様を確認する。'] }, { type: 'title', text: '現在のPSUの状態を読む', level: 3 }, { type: 'paragraph', html: '最小値未満のPSUは入力した構成に不足します。最小値と推奨値の間は余裕が小さく、推奨値以上なら実用的な余裕があります。大容量すぎる電源は必要以上の容量になる場合があります。' }, { type: 'title', text: '最小容量と推奨容量の違い', level: 3 }, { type: 'paragraph', html: '最小値は入力した推定値の下限であり、不確実な場合の購入目標とは限りません。推奨値はピークと将来の変更に対応する余裕を加えます。ケースのサイズとGPUコネクターも適合している必要があります。' }, { type: 'title', text: 'GPUの過渡負荷とプラットフォーム確認', level: 3 }, { type: 'paragraph', html: 'グラフィックスカードは持続電力の数値に現れない短いピークを発生させることがあります。マージンは計画に役立ちますが、メーカーの指示の代わりにはなりません。PCIeケーブル、ATX要件、保護機能、独立テストを確認してください。' }, { type: 'table', headers: ['計画状況', '方法', '確認事項'], rows: [['実測値がある', '実測値に適度な余裕を加える', '負荷、ピーク、コネクター'], ['新しいゲーミングPC', 'ボード電力と増設用の余裕を使う', 'GPUピーク、ケーブル、サイズ'], ['将来の増設を予定', '切り上げる前に成長マージンを増やす', 'ドライブ、カード、冷却、ケース'], ['不明なハードウェア', '保守的な値を使い最小容量で購入しない', 'メーカー仕様と電源テスト']] }, { type: 'title', text: 'この計算ツールで確認できないこと', level: 3 }, { type: 'paragraph', html: 'このツールは入力値から容量を推定します。特定の製品が本物か、静音か、十分に保護されているか、すべての過渡負荷で安全かは確認できません。公式仕様と信頼できるテストで最終製品を確認してください。' }],
  ui: { sceneKicker: 'エネルギーの星座', deckTitle: 'チャンネルを調整', deckHint: 'チャンネルを動かすと彫刻が反応します', presetsHeader: 'ビルドプリセット', officePreset: 'オフィス', gamingPreset: 'ゲーミング', highEndPreset: 'ハイエンド', workstationPreset: 'ワークステーション', miniPcPreset: 'ミニPC', componentsHeader: 'コンポーネント負荷', cpuWatts: 'プロセッサー', gpuWatts: 'グラフィックスカード', motherboardWatts: 'マザーボードとメモリ', storageWatts: 'ストレージ', fansWatts: 'ファンと冷却', peripheralsWatts: '周辺機器', currentPsuWatts: '現在のPSU容量', showAdvanced: '詳細な負荷を調整', hideAdvanced: '詳細な負荷を隠す', marginsHeader: '計画マージン', transientMargin: '瞬間負荷マージン', growthMargin: '増設マージン', wattsUnit: 'W', baseLoad: '基本負荷', minimumPsu: '最小PSU', recommendedPsu: '推奨PSU', currentPsu: '現在のPSU', headroom: '余裕', statusLabel: 'ビルド状態', statusInsufficient: '不足', statusTight: '余裕小', statusRecommended: '推奨', statusOversized: '過剰', summaryPrefix: '次のステップ:', diagramTitle: '電力観測所', currentMarker: '現在のPSU', minimumMarker: '最小', recommendedMarker: '推奨', adviceInsufficient: '推奨値以上のPSUを選び、グラフィックスカードのコネクターを確認してください。', adviceTight: '構成が上限に近づいています。増設の余裕が必要なら推奨値を選んでください。', adviceRecommended: '現在のPSUは計画目標を満たしています。コネクター、サイズ、プラットフォームを確認してください。', adviceOversized: '容量には十分な余裕があります。購入前に効率、設置スペース、コネクターを確認してください。', inputHint: '可能な場合は実測値を使ってください。結果は計画用の推定値であり、最終的なハードウェア仕様の確認に代わるものではありません。' },
};
