import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { PsuPowerRequirementUI } from '../ui';
import { bibliography } from '../bibliography';

const title = 'PSU 전력 요구량 계산기';
const description = '부품 소비 전력, 순간 부하 여유, 업그레이드 여유, 현재 장착된 PSU를 바탕으로 PC에 필요한 전원 용량을 추정합니다.';
const faq = [{ question: 'PC에 필요한 PSU 전력은 어떻게 계산하나요?', answer: '프로세서, 그래픽 카드, 메인보드, 스토리지, 팬, 주변기기의 예상 전력을 더합니다. 그다음 순간 부하 여유와 업그레이드 여유를 더하고 실용적인 PSU 용량으로 올림합니다.' }, { question: 'TDP와 측정 전력 중 무엇을 사용해야 하나요?', answer: '가능하면 측정값이나 제조사가 제시한 board power를 사용하세요. TDP는 계획용 값이며 모든 작업의 최대 소비를 보장하지 않습니다. 여유를 남기고 부품 사양을 확인하세요.' }, { question: '순간 부하 여유는 무엇을 의미하나요?', answer: '짧은 전력 상승과 지속 부하 추정의 불확실성을 반영합니다. 일반 소비량의 한계에 맞춰 PSU를 선택하는 일을 줄여 줍니다.' }, { question: '너무 큰 PSU가 나쁜 선택이 될 수 있나요?', answer: '과도하게 큰 PSU는 더 비싸고 효율이 좋은 작동 범위를 벗어날 수 있습니다. 크기, 커넥터, 레일, 플랫폼 호환성도 확인하세요.' }, { question: '최소 PSU와 권장 PSU의 차이는 무엇인가요?', answer: '최소 PSU는 계산된 부품 부하와 순간 부하 여유를 충족합니다. 권장 PSU는 업그레이드와 불확실성을 위한 추가 여유를 포함합니다.' }, { question: 'GPU 전력 스파이크는 PSU 선택에 어떤 영향을 주나요?', answer: '그래픽 카드는 지속 board power보다 높은 전력을 잠시 사용할 수 있습니다. 여유를 두고 제조사 지침, 커넥터, 과도 응답을 확인하세요.' }, { question: '와트 계산기만으로 PSU를 선택해도 되나요?', answer: '아니요. 크기, 커넥터, 호환성, 보호 기능, 효율 인증, 보증, 독립 품질 테스트도 확인해야 합니다.' }];
const howTo = [{ name: '부품 전력 입력하기', text: '프로세서, 그래픽 카드, 메인보드, 스토리지, 팬, 주변기기의 현실적인 값을 입력합니다.' }, { name: '현재 PSU 설정하기', text: '현재 PSU에 표시된 용량을 입력하거나 새 PC를 계획한다면 0을 입력합니다.' }, { name: '계획 여유 조정하기', text: '짧은 피크에는 순간 부하 여유를, 업그레이드에는 성장 여유를 사용합니다.' }, { name: '권장값 읽기', text: '최소값과 권장값을 현재 PSU와 비교하고 상태를 계획의 기준으로 사용합니다.' }, { name: '하드웨어 호환성 확인하기', text: '구매 전에 크기, 커넥터, GPU 요구 사항, 제조사 지침을 확인합니다.' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'KRW' }, inLanguage: 'ko' };

export const content: ToolLocaleContent<PsuPowerRequirementUI> = {
  slug: 'psu-power-requirement-calculator', title, description, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [{ type: 'title', text: 'PC용 PSU 전력 요구량 계산기', level: 2 }, { type: 'paragraph', html: '각 부품의 예상 부하를 바탕으로 PC에 필요한 PSU 용량을 추정합니다. 기본 부하, 순간 부하, 업그레이드 여유, 최소 용량, 권장 용량을 구분해 현재 PSU와 시스템 요구량을 비교할 수 있습니다.' }, { type: 'title', text: '전력 추정 방식', level: 3 }, { type: 'paragraph', html: '기본 부하는 프로세서, 그래픽 카드, 메인보드, 스토리지, 팬, 주변기기의 합계입니다. 짧은 피크와 미래의 변경을 위한 여유를 더한 뒤 실용적인 50W 단위로 올림합니다.' }, { type: 'table', headers: ['입력', '중요한 이유', '계획 기준'], rows: [['프로세서 전력', '지속 부하의 큰 부분을 결정', '패키지 전력 또는 측정값을 사용합니다.'], ['그래픽 카드 전력', '게임에서 가장 큰 부하인 경우가 많음', 'board power와 피크를 고려합니다.'], ['메인보드와 메모리', '플랫폼 소비를 포함', '칩셋, 메모리, 전원 회로, 내장 장치를 포함합니다.'], ['스토리지와 팬', '지속 부하와 시작 부하를 추가', '모든 드라이브, 펌프, 팬을 포함합니다.'], ['여유', '불확실성과 업그레이드에 대비', '데이터가 불확실하면 늘립니다.']] }, { type: 'title', text: '안전한 PSU 용량 선택', level: 3 }, { type: 'list', items: ['최소값과 권장값을 비교합니다.', 'PSU 크기와 커넥터를 확인합니다.', 'GPU 전력 특성을 지원하는지 확인합니다.', '결과는 추정치로 사용하고 최종 사양을 확인합니다.'] }, { type: 'title', text: '현재 PSU 상태 읽기', level: 3 }, { type: 'paragraph', html: '최소값보다 낮은 PSU는 부족합니다. 최소값과 권장값 사이에서는 여유가 작습니다. 권장 PSU는 실용적인 여유를 제공하고, 지나치게 큰 모델은 필요 이상의 용량을 제공할 수 있습니다.' }, { type: 'title', text: '최소 전력과 권장 전력', level: 3 }, { type: 'paragraph', html: '최소값은 입력한 추정치의 하한이며 데이터가 불확실할 때 항상 구매 목표가 되지는 않습니다. 권장값은 피크와 미래 변경을 위한 공간을 더합니다. 케이스 크기와 GPU 커넥터도 맞아야 합니다.' }, { type: 'title', text: 'GPU 과도 부하와 플랫폼 확인', level: 3 }, { type: 'paragraph', html: '그래픽 카드는 지속 전력 수치에 나타나지 않는 짧은 피크를 만들 수 있습니다. 여유는 계획에 도움을 주지만 제조사 지침을 대신하지 않습니다. PCIe 케이블, ATX 요구 사항, 보호 기능, 독립 테스트를 확인하세요.' }, { type: 'table', headers: ['상황', '접근 방법', '확인할 항목'], rows: [['측정값이 있음', '측정값에 적당한 여유를 더함', '부하, 피크, 커넥터'], ['새 게이밍 PC', 'board power와 성장 여유를 사용', 'GPU 피크, 케이블, 크기'], ['업그레이드 예정', '올림 전에 성장 여유를 늘림', '드라이브, 카드, 냉각, 케이스'], ['불확실한 하드웨어', '보수적인 값을 사용하고 최소값으로 구매하지 않음', '제조사 자료와 PSU 테스트']] }, { type: 'title', text: '이 계산기로 확인할 수 없는 것', level: 3 }, { type: 'paragraph', html: '이 도구는 입력값으로 용량을 추정합니다. 특정 제품의 정품 여부, 소음, 보호 기능, 케이스 적합성, 모든 과도 부하에서의 안전성을 확인할 수는 없습니다. 공식 사양과 신뢰할 수 있는 테스트로 최종 제품을 확인하세요.' }],
  ui: { sceneKicker: '에너지 별자리', deckTitle: '채널 조정', deckHint: '채널을 움직이면 조형물이 반응합니다', presetsHeader: '빌드 프리셋', officePreset: '오피스', gamingPreset: '게이밍', highEndPreset: '하이엔드', workstationPreset: '워크스테이션', miniPcPreset: '미니 PC', componentsHeader: '부품 부하', cpuWatts: '프로세서', gpuWatts: '그래픽 카드', motherboardWatts: '메인보드 및 메모리', storageWatts: '스토리지', fansWatts: '팬 및 냉각', peripheralsWatts: '주변기기', currentPsuWatts: '현재 PSU 용량', showAdvanced: '상세 부하 조정', hideAdvanced: '상세 부하 숨기기', marginsHeader: '계획 여유', transientMargin: '순간 부하 여유', growthMargin: '성장 여유', wattsUnit: 'W', baseLoad: '기본 부하', minimumPsu: '최소 PSU', recommendedPsu: '권장 PSU', currentPsu: '현재 PSU', headroom: '여유 용량', statusLabel: '빌드 상태', statusInsufficient: '부족', statusTight: '여유 부족', statusRecommended: '권장', statusOversized: '과대 용량', summaryPrefix: '다음 단계:', diagramTitle: '전력 관측소', currentMarker: '현재 PSU', minimumMarker: '최소', recommendedMarker: '권장', adviceInsufficient: '권장값 이상의 PSU를 선택하고 그래픽 카드 커넥터를 확인하세요.', adviceTight: '구성이 한계에 가깝습니다. 업그레이드 여유가 필요하면 권장값을 선택하세요.', adviceRecommended: '현재 PSU가 계획 목표를 충족합니다. 커넥터, 크기, 플랫폼을 확인하세요.', adviceOversized: '용량이 충분히 큽니다. 구매 전에 효율, 공간, 커넥터를 확인하세요.', inputHint: '가능하면 측정값을 사용하세요. 결과는 계획용 추정치이며 최종 하드웨어 사양 확인을 대신하지 않습니다.' },
};
