import type { FAQPage, HowTo, SoftwareApplication, WithContext } from 'schema-dts';
import type { ToolLocaleContent } from '../../../types';
import type { PsuPowerRequirementUI } from '../ui';
import { bibliography } from '../bibliography';

const title = '电源功率需求计算器';
const description = '根据组件功耗、瞬时负载余量、升级余量和现有电源容量，估算电脑所需的电源功率。';
const faq = [{ question: '如何计算电脑需要的电源功率？', answer: '先相加处理器、显卡、主板、存储、风扇和外设的预计功耗，再加入瞬时负载余量和升级余量，最后向上取整到实用的电源规格。' }, { question: '应该使用TDP还是实测功耗？', answer: '有条件时使用实测值或厂商提供的板卡功耗。TDP只是规划参考，并不保证每种负载下的最大功耗，因此仍要保留余量并检查组件规格。' }, { question: '瞬时负载余量是什么意思？', answer: '它用于覆盖短暂的功耗峰值和持续负载估算的不确定性，避免电源容量刚好卡在系统的正常功耗上。' }, { question: '电源容量过大为什么可能不是好选择？', answer: '严重超规格的电源可能更贵，并且偏离最佳效率区间。还要检查尺寸、接口、供电轨和平台兼容性。' }, { question: '最低电源和推荐电源有什么区别？', answer: '最低电源覆盖计算出的组件负载和瞬时余量。推荐电源还加入了升级空间，可以应对未来改动和估算误差。' }, { question: '显卡功耗峰值会怎样影响电源选择？', answer: '显卡可能在短时间内超过持续板卡功耗。请保留余量，查看厂商建议，并确认接口和电源的瞬态响应能力。' }, { question: '只看瓦数就能选择电源吗？', answer: '不能。还需要确认尺寸、接口、兼容性、保护功能、效率认证、保修和独立质量测试。' }];
const howTo = [{ name: '输入组件功耗', text: '为处理器、显卡、主板、存储、风扇和外设输入真实的功耗值。' }, { name: '设置当前电源', text: '输入现有电源标注的功率；如果是新装机计划，则输入零。' }, { name: '调整规划余量', text: '使用瞬时负载余量应对短暂峰值，使用增长余量应对升级和新增硬件。' }, { name: '查看推荐结果', text: '将最低值和推荐值与当前电源比较，并把状态作为规划参考。' }, { name: '检查硬件匹配', text: '购买前确认尺寸、接口、显卡要求和厂商建议。' }];
const faqSchema: WithContext<FAQPage> = { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faq.map((item) => ({ '@type': 'Question', name: item.question, acceptedAnswer: { '@type': 'Answer', text: item.answer } })) };
const howToSchema: WithContext<HowTo> = { '@context': 'https://schema.org', '@type': 'HowTo', name: title, description, step: howTo.map((step, index) => ({ '@type': 'HowToStep', position: index + 1, name: step.name, text: step.text })) };
const appSchema: WithContext<SoftwareApplication> = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: title, description, applicationCategory: 'UtilityApplication', operatingSystem: 'All', offers: { '@type': 'Offer', price: '0', priceCurrency: 'CNY' }, inLanguage: 'zh' };

export const content: ToolLocaleContent<PsuPowerRequirementUI> = {
  slug: 'psu-power-requirement-calculator', title, description, faq, bibliography, howTo, schemas: [faqSchema, howToSchema, appSchema],
  seo: [{ type: 'title', text: '电脑PSU电源功率需求计算器与选购指南', level: 2 }, { type: 'paragraph', html: '根据各个组件的预计负载准确估算电脑所需的电源（PSU）功率。本工具会分别清晰地显示系统基础负载、瞬时负载余量、未来升级余量、最低电源功率和推荐电源功率，方便您快速比较现有电源与整机实际硬件需求，避免因电源功率不足导致死机重启或容量过大浪费预算。' }, { type: 'title', text: '功率估算如何工作', level: 3 }, { type: 'paragraph', html: '基础负载是处理器、显卡、主板、内存、存储硬盘、风扇以及外设功耗的总和。随后系统加入短暂峰值和未来改动所需的预留余量，并向上取整到实用的50瓦档位规格。' }, { type: 'table', headers: ['输入项', '重要原因', '规划建议'], rows: [['处理器功耗', '决定持续负载的重要部分', '使用封装功耗或实测值。'], ['显卡功耗', '通常是游戏负载中最大的一项', '使用板卡功耗并考虑峰值。'], ['主板和内存', '覆盖平台本身的功耗', '包括芯片组、内存、供电和板载设备。'], ['存储和风扇', '增加持续功耗和启动功耗', '计算每个硬盘、泵 and 风扇。'], ['余量', '应对不确定性和升级', '数据不确定时适当增加。']] }, { type: 'title', text: '如何选择安全的电源容量', level: 3 }, { type: 'list', items: ['比较最低值和推荐值。', '确认电源尺寸和接口。', '确认电源能够应对显卡的功耗特性。', '把结果当作估算，并检查最终硬件规格。'] }, { type: 'title', text: '如何理解当前电源状态', level: 3 }, { type: 'paragraph', html: '低于最低值的电源无法满足输入配置。处于最低值和推荐值之间时余量较小。达到推荐值的电源提供实用空间，而容量过大的型号可能超出系统需求。' }, { type: 'title', text: '最低功率与推荐功率', level: 3 }, { type: 'paragraph', html: '最低值是输入估算的下限，在数据不确定时不一定适合作为购买目标。推荐值为峰值和未来变化预留空间。机箱尺寸和显卡接口也必须匹配。' }, { type: 'title', text: '显卡瞬态负载与平台检查', level: 3 }, { type: 'paragraph', html: '显卡可能产生简单持续功耗数字无法体现的短暂峰值。余量有助于规划，但不能替代厂商建议。请检查PCIe线缆、ATX要求、保护功能和独立测试。' }, { type: 'table', headers: ['规划情况', '处理方式', '需要确认'], rows: [['已有实测值', '使用实测值并保留适度余量', '负载、峰值和接口'], ['新游戏电脑', '使用板卡功耗并保留升级余量', '显卡峰值、线缆和尺寸'], ['计划未来升级', '在取整前增加增长余量', '硬盘、扩展卡、散热和机箱'], ['硬件信息不完整', '使用保守值，不要按最低值购买', '厂商资料和电源测试']] }, { type: 'title', text: '计算器无法确认的事项', level: 3 }, { type: 'paragraph', html: '工具只能根据输入值估算容量，无法确认某个型号是否正品、安静、保护完善、适合机箱，或能否应对所有瞬态模式。请使用官方规格和可靠的硬件测试验证最终产品。' }],
  ui: { sceneKicker: '能量星座', deckTitle: '调节通道', deckHint: '拖动通道，观察雕塑作出反应', presetsHeader: '装机预设', officePreset: '办公', gamingPreset: '游戏', highEndPreset: '高端', workstationPreset: '工作站', miniPcPreset: '迷你电脑', componentsHeader: '组件负载', cpuWatts: '处理器', gpuWatts: '显卡', motherboardWatts: '主板和内存', storageWatts: '存储', fansWatts: '风扇和散热', peripheralsWatts: '外设', currentPsuWatts: '当前电源功率', showAdvanced: '调整详细负载', hideAdvanced: '隐藏详细负载', marginsHeader: '规划余量', transientMargin: '瞬时负载余量', growthMargin: '升级余量', wattsUnit: 'W', baseLoad: '基础负载', minimumPsu: '最低电源', recommendedPsu: '推荐电源', currentPsu: '当前电源', headroom: '余量', statusLabel: '装机状态', statusInsufficient: '不足', statusTight: '偏紧', statusRecommended: '推荐', statusOversized: '过大', summaryPrefix: '下一步:', diagramTitle: '功率观测台', currentMarker: '当前电源', minimumMarker: '最低', recommendedMarker: '推荐', adviceInsufficient: '请选择不低于推荐值的电源，并确认显卡接口。', adviceTight: '系统接近上限。如果需要升级空间，请选择推荐值。', adviceRecommended: '当前电源达到规划目标。请确认接口、尺寸和平台。', adviceOversized: '容量很充足。购买前检查效率、空间和接口布局。', inputHint: '尽可能使用实测值。结果是规划估算，不能替代对最终硬件规格的检查。' },
};
