export { estimadorSaludBateria } from './tool/batteryHealthEstimator/entry';
export type { EstimadorSaludBateriaLocaleContent } from './tool/batteryHealthEstimator/entry';
export { pixelesPantalla } from './tool/deadPixelTest/entry';
export type { PixelesPantallaLocaleContent } from './tool/deadPixelTest/entry';
export { testMando } from './tool/gamepadTest/entry';
export type { TestMandoLocaleContent } from './tool/gamepadTest/entry';
export { probadorVibracionMando } from './tool/gamepadVibrationTester/entry';
export type { ProbadorVibracionMandoLocaleContent } from './tool/gamepadVibrationTester/entry';
export { testTeclado } from './tool/keyboardTest/entry';
export type { TestTecladoLocaleContent } from './tool/keyboardTest/entry';
export { testRaton } from './tool/mousePollingTest/entry';
export type { TestRatonLocaleContent } from './tool/mousePollingTest/entry';
export { toneGenerator } from './tool/toneGenerator/entry';
export type { ToneGeneratorLocaleContent } from './tool/toneGenerator/entry';
export { hardwareCategory } from './category';
import { estimadorSaludBateria } from './tool/batteryHealthEstimator/entry';
import { pixelesPantalla } from './tool/deadPixelTest/entry';
import { testMando } from './tool/gamepadTest/entry';
import { probadorVibracionMando } from './tool/gamepadVibrationTester/entry';
import { testTeclado } from './tool/keyboardTest/entry';
import { testRaton } from './tool/mousePollingTest/entry';
import { toneGenerator } from './tool/toneGenerator/entry';
export const ALL_ENTRIES = [estimadorSaludBateria, pixelesPantalla, testMando, probadorVibracionMando, testTeclado, testRaton, toneGenerator];
