export { estimadorSaludBateria } from './tool/batteryHealthEstimator/entry';
export type { EstimadorSaludBateriaLocaleContent } from './tool/batteryHealthEstimator/entry';
export { pixelesPantalla } from './tool/deadPixelTest/entry';
export type { PixelesPantallaLocaleContent } from './tool/deadPixelTest/entry';
export { testMando } from './tool/gamepadTest/entry';
export type { TestMandoLocaleContent } from './tool/gamepadTest/entry';
export { probadorVibracionMando } from './tool/gamepadVibrationTester/entry';
export type { ProbadorVibracionMandoLocaleContent } from './tool/gamepadVibrationTester/entry';
export { testTeclado } from './tool/keyboardTest/entry';
export type { TestTecladoLocaleContent } from './tool/keyboardTest/entry';
export { testRaton } from './tool/mousePollingTest/entry';
export type { TestRatonLocaleContent } from './tool/mousePollingTest/entry';
export { mouseDoubleClickTest } from './tool/mouseDoubleClickTest/entry';
export type { MouseDoubleClickTestLocaleContent } from './tool/mouseDoubleClickTest/entry';
export { mouseScrollTest } from './tool/mouseScrollTest/entry';
export type { MouseScrollTestLocaleContent } from './tool/mouseScrollTest/entry';
export { toneGenerator } from './tool/toneGenerator/entry';
export type { ToneGeneratorLocaleContent } from './tool/toneGenerator/entry';
export { refreshRateDetector } from './tool/refreshRateDetector/entry';
export type { RefreshRateDetectorLocaleContent } from './tool/refreshRateDetector/entry';
export { monitorGhostingTest } from './tool/monitorGhostingTest/entry';
export type { MonitorGhostingTestLocaleContent } from './tool/monitorGhostingTest/entry';
export { spectrumCanvas } from './tool/colorAccuracyTest/entry';
export type { SpectrumCanvasLocaleContent } from './tool/colorAccuracyTest/entry';
export { upsRuntimeCalculator } from './tool/upsRuntimeCalculator/entry';
export type { UpsRuntimeCalculatorLocaleContent } from './tool/upsRuntimeCalculator/entry';
export { stereoAudioTest } from './tool/stereoAudioTest/entry';
export type { StereoAudioTestLocaleContent } from './tool/stereoAudioTest/entry';
export { webBluetoothBleScanner } from './tool/webBluetoothBleScanner/entry';
export type { WebBluetoothBleScannerLocaleContent } from './tool/webBluetoothBleScanner/entry';
export { keyboardChatterTest } from './tool/keyboardChatterTest/entry';
export type { KeyboardChatterTestLocaleContent } from './tool/keyboardChatterTest/entry';
export { webUsbSerialMonitor } from './tool/webUsbSerialMonitor/entry';
export type { WebUsbSerialMonitorLocaleContent } from './tool/webUsbSerialMonitor/entry';
export { hardwareCategory } from './category';
import { estimadorSaludBateria } from './tool/batteryHealthEstimator/entry';
import { pixelesPantalla } from './tool/deadPixelTest/entry';
import { testMando } from './tool/gamepadTest/entry';
import { probadorVibracionMando } from './tool/gamepadVibrationTester/entry';
import { testTeclado } from './tool/keyboardTest/entry';
import { testRaton } from './tool/mousePollingTest/entry';
import { mouseDoubleClickTest } from './tool/mouseDoubleClickTest/entry';
import { mouseScrollTest } from './tool/mouseScrollTest/entry';
import { toneGenerator } from './tool/toneGenerator/entry';
import { refreshRateDetector } from './tool/refreshRateDetector/entry';
import { monitorGhostingTest } from './tool/monitorGhostingTest/entry';
import { spectrumCanvas } from './tool/colorAccuracyTest/entry';
import { upsRuntimeCalculator } from './tool/upsRuntimeCalculator/entry';
import { stereoAudioTest } from './tool/stereoAudioTest/entry';
import { webBluetoothBleScanner } from './tool/webBluetoothBleScanner/entry';
import { keyboardChatterTest } from './tool/keyboardChatterTest/entry';
import { webUsbSerialMonitor } from './tool/webUsbSerialMonitor/entry';
export const ALL_ENTRIES = [estimadorSaludBateria, pixelesPantalla, testMando, probadorVibracionMando, testTeclado, keyboardChatterTest, testRaton, mouseDoubleClickTest, mouseScrollTest, toneGenerator, refreshRateDetector, monitorGhostingTest, spectrumCanvas, upsRuntimeCalculator, stereoAudioTest, webBluetoothBleScanner, webUsbSerialMonitor];
