export { ALL_ENTRIES } from './entries';
import type { ToolDefinition } from './types';
import { PIXELES_PANTALLA_TOOL } from './tool/deadPixelTest/index';
import { TEST_TECLADO_TOOL } from './tool/keyboardTest/index';
import { TEST_MANDO_TOOL } from './tool/gamepadTest/index';
import { PROBADOR_VIBRACION_MANDO_TOOL } from './tool/gamepadVibrationTester/index';
import { TEST_RATON_TOOL } from './tool/mousePollingTest/index';
import { ESTIMADOR_SALUD_BATERIA_TOOL } from './tool/batteryHealthEstimator/index';
import { TONE_GENERATOR_TOOL } from './tool/toneGenerator/index';
import { REFRESH_RATE_DETECTOR_TOOL } from './tool/refreshRateDetector/index';
import { SPECTRUM_CANVAS_TOOL } from './tool/colorAccuracyTest/index';
import { MOUSE_DOUBLE_CLICK_TEST_TOOL } from './tool/mouseDoubleClickTest/index';
import { MOUSE_SCROLL_TEST_TOOL } from './tool/mouseScrollTest/index';
import { MOUSE_DPI_ANALYZER_TOOL } from './tool/mouseDpiAnalyzer/index';
import { MONITOR_GHOSTING_TEST_TOOL } from './tool/monitorGhostingTest/index';
import { BACKLIGHT_BLEED_BLOOMING_TEST_TOOL } from './tool/backlightBleedBloomingTest/index';
import { UPS_RUNTIME_CALCULATOR_TOOL } from './tool/upsRuntimeCalculator/index';
import { STEREO_AUDIO_TEST_TOOL } from './tool/stereoAudioTest/index';
import { WEB_BLUETOOTH_BLE_SCANNER_TOOL } from './tool/webBluetoothBleScanner/index';
import { WEBMIDI_KEYBOARD_TESTER_TOOL } from './tool/webMidiKeyboardTester/index';
import { KEYBOARD_CHATTER_TEST_TOOL } from './tool/keyboardChatterTest/index';
import { WEB_USB_SERIAL_MONITOR_TOOL } from './tool/webUsbSerialMonitor/index';
import { USB_POWER_BUDGET_CALCULATOR_TOOL } from './tool/usbPowerBudgetCalculator/index';
import { MOBILE_SENSOR_TEST_TOOL } from './tool/mobileSensorTest/index';
import { SUBWOOFER_CROSSOVER_TEST_TOOL } from './tool/subwooferCrossoverTest/index';
import { MOUSE_JITTER_ANGLE_SNAPPING_TEST_TOOL } from './tool/mouseJitterAngleSnappingTest/index';

export const ALL_TOOLS: ToolDefinition[] = [PIXELES_PANTALLA_TOOL, TEST_TECLADO_TOOL, KEYBOARD_CHATTER_TEST_TOOL, WEBMIDI_KEYBOARD_TESTER_TOOL, TEST_MANDO_TOOL, PROBADOR_VIBRACION_MANDO_TOOL, TEST_RATON_TOOL, MOUSE_DOUBLE_CLICK_TEST_TOOL, MOUSE_SCROLL_TEST_TOOL, MOUSE_DPI_ANALYZER_TOOL, MOUSE_JITTER_ANGLE_SNAPPING_TEST_TOOL, ESTIMADOR_SALUD_BATERIA_TOOL, TONE_GENERATOR_TOOL, SUBWOOFER_CROSSOVER_TEST_TOOL, REFRESH_RATE_DETECTOR_TOOL, MONITOR_GHOSTING_TEST_TOOL, BACKLIGHT_BLEED_BLOOMING_TEST_TOOL, SPECTRUM_CANVAS_TOOL, UPS_RUNTIME_CALCULATOR_TOOL, USB_POWER_BUDGET_CALCULATOR_TOOL, MOBILE_SENSOR_TEST_TOOL, STEREO_AUDIO_TEST_TOOL, WEB_BLUETOOTH_BLE_SCANNER_TOOL, WEB_USB_SERIAL_MONITOR_TOOL];
